#cloud-config
autoinstall:
  version: 1
  
  locale: "de_DE"
  
  keyboard:
    layout: "de"
    variant:

  network:
    version: 2
    ethernets: {}

  identity:
    hostname: ""
    password: "${DEFAULT_USER_PASSWORD}"
    username: "sysadmin"

  storage:
    layout:
      name: lvm

  ssh:
    install-server: yes
    allow-pw: no
    authorized-keys:
      - "${DEFAULT_USER_SSH_KEY}"

  packages:
    - curl
    - python3-minimal
    - python3-pip
