#cloud-config
autoinstall:
  version: 1
  
  locale: "de_DE"
  
  keyboard:
    layout: "de"

  network:
    version: 2
    ethernets: {}

  identity:
    hostname: ""
    password: "${DEFAULT_USER_PASSWORD}"
    username: "sysadmin"

  storage:
    layout:
      name: lvm

  ssh:
    install-server: yes
    allow-pw: no
    authorized-keys:
      - "${DEFAULT_USER_SSH_KEY}"
      
  apt:
    preserve_source_list: false
    primary:
      - arches: [i386, amd64]
        uri: "http://archive.ubuntu.com/ubuntu
      - arches: [default]
        uri: "http://ports.ubuntu.com/ubuntu-ports
    geoip: true
    
  packages:
    - curl
    - python3-minimal
    - python3-pip
    - postfix
